### ISSUE TITLE
Include radius in location searching

### ISSUE THREAD

**Issue by AnthonyLia** [cwwmbm/linkedinscraper#1]
Hi, thanks for the repo. In this line:

`url = f"https://www.linkedin.com/jobs-guest/jobs/api/seeMoreJobPostings/search?keywords={keywords}&location={location}&f_TPR=&f_WT={query['f_WT']}&geoId=&f_TPR={config['timespan']}&start={25*i}"`

Is there a way to include '&distance={dist_num}' into the URL? I don't have experience with the jobs-guest/jobs/api search, as I've only used the front end, but I'd like to have control over that specific of the search.

Thanks!

**Comment by cwwmbm** [comment]
This is currently impossible to do due to LinkedIn limitations
