### ISSUE TITLE
A Bug Report

### ISSUE THREAD

**Issue by codeadvance** [cwwmbm/linkedinscraper#6]
The website " https://jobbix.co/jobs " that you provided doesn't work once I signed up on the website. I have tried to create the job search but it is still blank.

**Comment by cwwmbm** [comment]
I can't do anything about this without more info. Screenshots, what you did, etc. So far it has been working for 800+ users and counting.

**Comment by cwwmbm** [comment]
Closing as this issue (if there's even an issue) doesn't relate to this repo
